apiVersion: apps/v1
kind: Deployment
metadata:
    name: travel-app-frontend
spec:
    replicas: 2
    selector:
        matchLabels:
            app: travel-app-frontend
    template:
        metadata:
            labels:
                app: travel-app-frontend
        spec:
            containers:
                - name: travel-app-frontend
                  image: ryanjgani/travel-app-frontend:prod_v1 # change to your image name
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: travel-app-frontend-svc
spec:
    type: NodePort
    selector:
        app: travel-app-frontend
    ports:
        - port: 80
          protocol: TCP
          targetPort: 80
          nodePort: 31000
