name: Continuous Deployment

on:
    push:
        branches: [master]

jobs:
    deployment:
        name: Server Deployment on DigitalOcean & Client Deployment on Netlify
        runs-on: ubuntu-latest
        steps:
            - name: Execute updates for the DigitalOcean server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  script: bash deployment.sh
            - name: Trigger Netlify Build Hook
              uses: wei/curl@v1
              with:
                  args: -X POST https://api.netlify.com/build_hooks/634250dea145c45407ad3a49
