name: Digital Ocean Continuous Deployment

on:
    push:
        branches: [master]

jobs:
    deployment:
        name: Deployment on DigitalOcean Server
        runs-on: ubuntu-latest
        steps:
            - name: Execute updates for the DigitalOcean server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  port: ${{ secrets.PORT }}
                  script: bash deployment.sh
